global using Microsoft.AspNetCore.Mvc;
global using Serilog;
global using System.Text;
// global using Microsoft.AspNetCore.Authentication.JwtBearer;
// global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Identity;
global using System.IdentityModel.Tokens.Jwt;
global using Microsoft.IdentityModel.Tokens;
global using System.Net;
global using System.Text.Json;
global using Serilog.Events;
global using Serilog.Context;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore;
global using System.Xml;
global using System.Security.Cryptography;
global using System.Security.Claims;
global using Microsoft.AspNetCore.Authorization;
global using System.Dynamic;
global using System.Globalization;
global using System.Data;
global using System.Linq.Dynamic.Core;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Text.Json.Serialization;
global using System.Collections.Generic;
global using System.Collections;
global using Microsoft.Extensions.Options;
global using AutoMapper;
global using Stripe;
global using Stripe.Checkout;

// -------------------------------------------------------------------

global using LMS_Demo.src.Middlewares;
global using LMS_Demo.src.Scripts;
global using LMS_Demo.src.Models;
global using LMS_Demo.src.Extensions.Setup;
global using LMS_Demo.src.Configurations;
global using LMS_Demo.src.Dtos;
global using LMS_Demo.src.Repos;
global using LMS_Demo.src.Extensions;
